name: SkyView
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
   
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main.jpg"