name: SkyView
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_rating_bar: ^4.0.1
  flutter_sequence_animation: ^4.0.0
  flutter_translate: ^4.0.4
  geolocator: ^11.0.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^25.2.3+1
  timezone: ^0.9.3
  http: ^0.13.3
  gallery_saver: ^2.3.2
  workmanager: ^0.5.2
  home_widget: ^0.6.0
  davinci: ^2.1.1 

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/intro/
    - assets/images/
    - assets/signs/
   
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main.jpg"